name: 'Clean Runner Environment'
description: 'Cleans workspace, Xcode cache/derived data, simulators and Xcode installations for Github runners'
author: 'Alessandro Basso'
inputs: 
  workspace:
    description: 'The GitHub workspace directory'
    required: true
    default: '${{ github.workspace }}'
runs:
  using: 'composite'
  steps:
    - name: Clean Workspace and Cache
      shell: bash
      run: |
        echo "Cleaning workspace directory (${{ inputs.workspace }})"
        sudo rm -rf "${{ inputs.workspace }}" > /dev/null
        mkdir -p "${{ inputs.workspace }}"

        echo "Cleaning simulators"
        xcrun simctl delete unavailable

        echo "Cleaning Xcode cache and derived data"
        rm -rf ~/Library/Developer/Xcode/DerivedData/*
        rm -rf ~/Library/Caches/com.apple.dt.Xcode/*

        echo "Cleaning Xcode installations"
        sudo rm -rf /Applications/Xcode_16.1_beta.app
        sudo rm -rf /Applications/Xcode_16_beta_6.app
        sudo rm -rf /Applications/Xcode_15.1.app
        sudo rm -rf /Applications/Xcode_15.3.app
        sudo rm -rf /Applications/Xcode_15.4.app
        sudo rm -rf /Applications/Xcode_15.0.1.app
        sudo rm -rf /Applications/Xcode_14.3.1.app
        sudo rm -rf /Applications/Xcode_14.2.app
        sudo rm -rf /Applications/Xcode_14.1.app

        #echo "Cleaning temporary files"
        #sudo rm -rf /tmp/* || true
        
        echo "Cleanup complete!"

        echo "Disk space after cleanup:"
        df -h