name: 'Clean Runner Environment'
description: 'Cleans workspace, Xcode cache/derived data, simulators, and Xcode installations for GitHub runners'
author: 'Alessandro Basso'
inputs: 
  workspace:
    description: 'The GitHub workspace directory to clean'
    required: false
    default: '${{ github.workspace }}'
  #xcode_version:
  #  description: 'The Xcode version to keep installed'
  #  required: false
  #  default: '15.2'
runs:
  using: 'composite'
  steps:
    - name: Clean Workspace and Cache
      shell: bash
      run: |
        # Uncomment to check disk space before cleanup
        #echo "Disk space before cleanup:"
        #df -h

        # Check if workspace directory is set before cleaning
        if [ -n "${{ inputs.workspace }}" ]; then
          echo "Cleaning workspace directory (${{ inputs.workspace }})"
          sudo rm -rf "${{ inputs.workspace }}" > /dev/null 2>&1
          mkdir -p "${{ inputs.workspace }}"
        else
          echo "Workspace directory is not set. Skipping workspace cleanup."
        fi

        #echo "Cleaning simulators"
        #xcrun simctl delete unavailable

        #echo "Cleaning Xcode cache and derived data"
        #rm -rf ~/Library/Developer/Xcode/DerivedData/*
        #rm -rf ~/Library/Caches/com.apple.dt.Xcode/*

        # Uncomment to list Xcode versions before cleanup
        #echo "Listing Xcode versions before cleanup:"
        #find /Applications -maxdepth 1 -type d -name "Xcode*.app" -exec basename {} \;

        #echo "Cleaning Xcode installations except Xcode_${{ inputs.xcode_version }}.app"
        #for xcode in /Applications/Xcode*.app; do
        #  if [[ "$xcode" != "/Applications/Xcode_${{ inputs.xcode_version }}.app" ]]; then
        #    echo " - Removing $xcode"
        #    sudo rm -rf "$xcode"
        #  fi
        #done

        echo "Cleanup complete!"

        # Uncomment to check disk space after cleanup
        #echo "Disk space after cleanup:"
        #df -h
