name: 'Clean Runner Environment'
description: 'Cleans workspace, Xcode cache/derived data, simulators and Xcode installations for Github runners'
author: 'Alessandro Basso'
inputs: 
  workspace:
    description: 'The GitHub workspace directory'
    required: true
    default: '${{ github.workspace }}'
runs:
  using: 'composite'
  steps:
    - name: Clean Workspace and Cache
      shell: bash
      run: |
        echo "Cleaning workspace directory (${{ inputs.workspace }})"
        sudo rm -rf "${{ inputs.workspace }}"
        mkdir -p "${{ inputs.workspace }}"

        echo "Cleaning simulators"
        xcrun simctl delete unavailable

        echo "Cleaning Xcode cache and derived data"
        rm -rf ~/Library/Developer/Xcode/DerivedData/*
        rm -rf ~/Library/Caches/com.apple.dt.Xcode/*

        echo "Cleaning Xcode installations"
        sudo rm -rf /Applications/Xcode_*.app

        echo "Cleaning temporary files"
        sudo rm -rf /tmp/*
        
        echo "Cleanup complete!"
